spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillhub
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    com.skillhub: DEBUG
